spring.application.name=spring-boot-crud-for-react-hooks-and-formik
spring.main.banner-mode=off
logging.level.root[0]=info
logging.level.root[1]=debug
# set log of jdbc if you wanna see what statement is executing
logging.level.org.springframework.jdbc.core=trace
spring.config.import=classpath:info/db.properties
#Note! some name can't use for var as driver,username,password fix by add prefix! ex, <prefix>.driver
#Note! mvn run and pass param only work on cmd not terminal
#mvn spring-boot:run -Dspring-boot.run.arguments="--mysql.driver=com.mysql.cj.jdbc.Driver , --mysql.url=jdbc:mysql://127.0.0.1:3306/apply_custom_services , --mysql.username=ttknp , --mysql.password=12345"
#java -jar apply-custom-services-0.0.1-SNAPSHOT.jar --mysql.url=jdbc:mysql://localhost:3306/apply_custom_services --mysql.username=ttknp --mysql.password=12345 --mysql.driver=com.mysql.cj.jdbc.Driver
spring.datasource.driver-class-name=${mysql.driver}
spring.datasource.url=${mysql.url}
spring.datasource.username=${mysql.username}
spring.datasource.password=${mysql.password}
#
target.images.dir=B:\\practice-nodejs-php-typescript-angular\\applications\\Project-React\\lab-react-hooks-and-formik-for-spring-boot-crud\\src\\assets\\images